export const SocketEnums = {
    ClientRegister: 0,
    AdminHide: 1,
    AdminShow: 2,
    AdminShowCiv: 3,
    AdminHideCiv: 4,
    AdminShowAll: 5,
    AdminHideAll: 6,
    AdminShowTech: 7,
    AdminHideTech: 8,
    AdminShowBlacksmith: 9,
    AdminHideBlacksmith: 10,
    AdminShowUniversity: 11,
    AdminHideUniversity: 12,
    AdminShowMonastary: 13,
    AdminHideMonastary: 14,
    AdminShowDock: 15,
    AdminHideDock: 16,
    AdminShowBracket: 17,
    AdminHideBracket: 18,
    AdminShowMaps: 19,
    AdminHideMaps: 20,
    AdminShowPlayerPicks: 21,
    AdminHidePlayerPicks: 22,
    OverlayPlayerInfo: 23,
    PING: 24
}